### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by lo69420** [useragents/Instagram-Username-Auto-Claimer#1]
i dont know what you mean by Put your proxies inside of proxies.txt. what are proxies?

**Comment by Al3xlol** [comment]
> 

Hello proxies are like virtual ips so you don’t get rate limited by Instagram if you don’t have paid proxies it’s pointless

**Comment by lo69420** [comment]
ohh :(

**Comment by useragents** [comment]
Make a file named `proxies.txt` and put your proxy list (IP:port) in there.
