### ISSUE TITLE
Proxies.txt file not found

### ISSUE THREAD

**Issue by x198x** [useragents/Instagram-Username-Auto-Claimer#10]
when i run the claim.py it says [Console] File proxies.txt not found and there is a proxies.txt file and has proxies in it

![image](https://user-images.githubusercontent.com/103961480/163873430-347658c8-04df-485e-8134-70d4be19ba81.png)

![image](https://user-images.githubusercontent.com/103961480/163873458-7b7ff308-c361-4f5b-87d2-57177e966801.png)

**Comment by useragents** [comment]
I'm not sure why this may occur, for whatever reason, Python cannot find the `proxies.txt` file in the same directory.
