### ISSUE TITLE
 [Console] File proxies.txt not found

### ISSUE THREAD

**Issue by x198x** [useragents/Instagram-Username-Auto-Claimer#12]
There is a proxies list with proxies and i have also extracted this , installed all requirements and is still showing this

**Comment by useragents** [comment]
The file must be `proxies.txt`, some people often set the file as `proxies.txt.txt` without noticing because some users may have file extensions shown off. If you are certain that the file is `proxies.txt`, for whatever reason, Python cannot find the file in the directory.
