### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by xqwiz** [useragents/Instagram-Username-Auto-Claimer#13]
I'm kind of dumb and I got this help pls

sh: 1: cls: not found
Traceback (most recent call last):
  File "/home/Instagram-Username-Auto-Claimer/claim.py", line 188, in <module>
    obj.main()
  File "/home/Instagram-Username-Auto-Claimer/claim.py", line 164, in main
    ctypes.windll.kernel32.SetConsoleTitleW("Instagram Auto Claimer | Developed by @useragents on Github")
AttributeError: module 'ctypes' has no attribute 'windll'

**Comment by useragents** [comment]
This is because this script does not support Linux, I have added Linux support in the latest version. Download it [here](https://github.com/useragents/Instagram-Username-Auto-Claimer/archive/refs/heads/main.zip) 👍
