### ISSUE TITLE
Error while downloading requirements

### ISSUE THREAD

**Issue by shdgdfghfdh** [useragents/Instagram-Username-Auto-Claimer#20]
when i went to cmd and typed what you said it said Fatal error in launcher: Unable to create process using

**Comment by useragents** [comment]
This issue has been closed as it is not related to my script. Please google your error before making an issue here, check this StackOverflow question [here](https://stackoverflow.com/questions/37220055/pip-fatal-error-in-launcher-unable-to-create-process-using).
