### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by ashwin8353** [useragents/Instagram-Username-Auto-Claimer#23]
which type of proxies should i used: HTTP, socks4, socks5?
anonymity: elite, anonymous, transparent?
can i get some proxy please
please send me to my instagram: @ashwinpaulofficial

**Comment by useragents** [comment]
I cannot provide proxies for you, the proxy type is HTTPS.

**Comment by future4772** [comment]
Hi
How can I make 3L username in Instagram 
Please guide me
THANK YOU
