### ISSUE TITLE
Which type of usernames can be claimed?

### ISSUE THREAD

**Issue by ashwin8353** [useragents/Instagram-Username-Auto-Claimer#25]
Taken usernames?
Untaken usernames?
Disabled accounts?
how do i know which usernames available?

**Comment by 9xN** [comment]
are you fucking retarded

**Comment by useragents** [comment]
For example, if you attempt to auto claim a specific user and it is currently taken, the script will keep retrying until it is available. This script will **not** work on usernames that have been disabled considering they will never be available again.
