### ISSUE TITLE
Getting error Message !! URGENT

### ISSUE THREAD

**Issue by HackersBun** [useragents/Instagram-Username-Auto-Claimer#30]
![image](https://user-images.githubusercontent.com/110983638/183901836-9f13660d-fcaf-4023-93ba-bb4db8f6674c.png)
I am getting the error message while I try to use this code. 
What could go wrong?
I have installed all the requirements and entered the right user name and password,

**Comment by votlng** [comment]
Hi HackerBun,

By the looks of the error you got if you have 2fa enabled on the account take it off then run the code

**Comment by HackersBun** [comment]
Thank you for replying. However, I have not enabled the 2FA on that particular account !

**Comment by HackersBun** [comment]
![1223](https://user-images.githubusercontent.com/110983638/188145428-5d873192-0da5-411b-beea-608143404f6e.JPG)

I shows successfully logged in but getting the error message again !

**Comment by future4772** [comment]
Hi
How can I make 3L username in Instagram 
Please guide me
THANK YOU

**Comment by Pietys** [comment]
it triggers a sus login, would recommend adding a part where it can receive a code to input

**Comment by useragents** [comment]
Suspicious login / checkpoint_required = Login normally on the same IP on a browser then retry.
The issue with email is fixed.
