### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by guedesz** [useragents/Instagram-Username-Auto-Claimer#4]
You should add the 14 days bypass hold in your tool. It would be amazing

**Comment by useragents** [comment]
Does it not bypass it? @guedesz

**Comment by guedesz** [comment]
I don't think so, I've tried claiming a random user I created and didn't work

**Comment by useragents** [comment]
You're right, I must've forgotten to add it in. I'll do that now 👍

**Comment by useragents** [comment]
Download the new version [here](https://github.com/useragents/Instagram-Username-Auto-Claimer/archive/refs/heads/main.zip).
