### ISSUE TITLE
Closes

### ISSUE THREAD

**Issue by urmum33** [useragents/Instagram-Username-Auto-Claimer#5]
a bunch of code shows up then closes

**Comment by useragents** [comment]
Download the new version [here](https://github.com/useragents/Instagram-Username-Auto-Claimer/archive/refs/heads/main.zip) and tell me what error you get.

**Comment by urmum33** [comment]
the eror is {"message":"","two_factor_required":true,"two_factor_info":{"pk":45304400557,"username":"aspect_yn","sms_two_factor_on":true,"whatsapp_two_factor_on":false,"totp_two_factor_on":false,"eligible_for_multiple_totp":true,"obfuscated_phone_number":"8043","two_factor_identifier":"(my personal info)","show_messenger_code_option":false,"show_new_login_screen":true,"show_trusted_device_option":false,"should_opt_in_trusted_device_option":true,"pending_trusted_notification":false,"sms_not_allowed_reason":null,"trusted_notification_polling_nonce":null,"is_trusted_device":false,"phone_verification_settings":{"max_sms_count":2,"resend_sms_delay_sec":60,"robocall_count_down_time_sec":30,"robocall_after_max_sms":true}},"phone_verification_settings":{"max_sms_count":2,"resend_sms_delay_sec":60,"robocall_count_down_time_sec":30,"robocall_after_max_sms":true},"status":"fail","error_type":"two_factor_required"}

**Comment by urmum33** [comment]
and then a bunch of messages from facebook come through

**Comment by cartelics** [comment]
just do the same thing make sure you download the requirements and run it with python.

**Comment by useragents** [comment]
Turn off 2FA, then retry. If the device is not recognized `(checkpoint_required)` then log in on a browser, then use the script with the same IP address.
