### ISSUE TITLE
cant run 

### ISSUE THREAD

**Issue by fuutives** [useragents/Instagram-Username-Auto-Claimer#6]
after downloading recuirements.txt its saying in the script: 
Error while importing modules. Please install the modules in requirements.tkt
what can i do?

**Comment by TheGamer456YT** [comment]
open cmd/powershell, go to the folder where you installed the program by typing "cd path\to\folder", then run pip install -r requirements.txt

**Comment by useragents** [comment]
Type the following into Command Prompt if you cannot download the modules from requirements.txt:
`pip install colorama`
`pip install requests`

**Comment by future4772** [comment]
Hi
How can I make 3L username in Instagram 
Please guide me
THANK YOU
